name: Deploy API to dev environment

on:
  push:
    branches:
      - dev
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: dev

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Deploy CloudFormation Stack
        env:
          STAGE: dev
        run: aws cloudformation deploy --template-file infra/cloudformation-template.yaml --stack-name marble-api-$STAGE --capabilities CAPABILITY_NAMED_IAM --parameter-overrides STAGE=$STAGE AWSACCESSKEY=${{ secrets.AWS_ACCESS_KEY }} AWSSECRETACCESSKEY=${{ secrets.AWS_SECRET_ACCESS_KEY }} DBHOST="${{ secrets.DB_HOST }}" DBUSERNAME=${{ secrets.DB_USERNAME }} DBPASSWORD=${{ secrets.DB_PASSWORD }} JWTSECRET=${{ secrets.JWT_SECRET }} OPENAIAPIKEY="${{ secrets.OPENAI_API_KEY }}" RAGAPIKEY="${{ secrets.RAG_API_KEY }}" CONTRACTRAGAPIKEY="${{ secrets.CONTRACT_RAG_API_KEY }}" STRIPESECRETKEY="${{ secrets.STRIPE_SECRET_KEY }}" STRIPEINDIVIDUALMONTHLYPRICEID=price_1PWcOZKcumHzyx15iPXSU1EJ STRIPESMALLBUSINESSMONTHLYPRICEID=price_1PQuKuKcumHzyx15nLKkelyh STRIPESOLOPRACTIONERMONTHLYPRICEID=price_1PQuMAKcumHzyx15242ia3RY STRIPEINDIVIDUALYEARLYPRICEID=price_1PWcjKKcumHzyx15QDv8JSPE STRIPESMALLBUSINESSYEARLYPRICEID=price_1PQuLCKcumHzyx15vOr4Reld STRIPESOLOPRACTIONERYEARLYPRICEID=price_1PQuMAKcumHzyx158GQv610F STRIPEAIASSISTANTPRICEID=price_1PT6neKcumHzyx15iHzFKiuY STRIPECONTRACTGENERATIONPRICEID=price_1PT6oYKcumHzyx15dtZbwbdp STRIPECONTRACTANALYSISPRICEID=price_1PT6pCKcumHzyx15PK5ErH9B STRIPEBUSINESSENTITYPRICEID=price_1PT6pjKcumHzyx154X6BPHfG STRIPEATTORNEYREVIEWPRICEID=price_1PT6qJKcumHzyx15TuJGghQm STRIPEWEBHOOKSIGNSECRET=${{ secrets.STRIPE_WEBHOOK_SIGN_SECRET }} ASSETSBUCKETNAME=dev.assets.marblels.com SERVERCOUNT=1 LBCERTIFICATE=arn:aws:acm:us-east-1:339712796640:certificate/5bbbe466-dffb-4b4e-ac04-19fafea4f80d

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      - name: Build and Push Docker Image to ECR
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          ECR_REPOSITORY: marble-ecr-dev
          IMAGE_TAG: latest
        run: |
          docker build -f ./Dockerfile . -t $ECR_REPOSITORY:$IMAGE_TAG
          docker tag $ECR_REPOSITORY:$IMAGE_TAG $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG
          docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG

      - name: Trigger ECS Service for deployment
        env:
          STAGE: dev
        run: aws ecs update-service --cluster marble-ecs-cluster-${STAGE} --service marble-ecs-api-service-${STAGE} --force-new-deployment
